---
title: "R Notebook"
output: html_notebook
---

```{r}
library(plotly)
library(dbplyr)
library(plyr)
library(stringi)
library(Rtsne)
library(gridExtra)  
library(ggplot2)
library(reshape2)
library(data.table)
library(tidyverse)
library(conStruct)

```

```{r}
Q2 <- read.table("../admix/ORIEN_TCGA.8.Q", head = FALSE,  sep = " ", stringsAsFactors = FALSE)
raw_fam2 <- read.table("../admix/ORIEN_TCGA.fam", head = FALSE, sep = " ", stringsAsFactors = FALSE)
raw_fam2 <- raw_fam2[,c(1,2)]
names(raw_fam2)[1] <- "indivID"
raw_fam2$order <- 1:nrow(raw_fam2) 
Q2$order <- 1:nrow(Q2) 
samples <- merge(Q2,raw_fam2,by="order")
samples <-samples[,c(10,2:9)]
names(samples)[2] <- "Q1"
names(samples)[3] <- "Q2"
names(samples)[4] <- "Q3"
names(samples)[5] <- "Q4"
names(samples)[6] <- "Q5"
names(samples)[7] <- "Q6"
names(samples)[8] <- "Q7"
names(samples)[9] <- "Q8"
```

```{r}
sample_coord1 <- read.table(file = '../laser/results.1-1250.ProPC.coord', sep = '\t', header = TRUE)
sample_coord2 <- read.table(file = '../laser/results.1251-2500.ProPC.coord', sep = '\t', header = TRUE)
sample_coord3 <- read.table(file = '../laser/results.2501-3750.ProPC.coord', sep = '\t', header = TRUE)
sample_coord4 <- read.table(file = '../laser/results.3751-5000.ProPC.coord', sep = '\t', header = TRUE)
sample_coord5 <- read.table(file = '../laser/results.5001-6250.ProPC.coord', sep = '\t', header = TRUE)
sample_coord6 <- read.table(file = '../laser/results.6251-7500.ProPC.coord', sep = '\t', header = TRUE)
sample_coord7 <- read.table(file = '../laser/results.7501-8750.ProPC.coord', sep = '\t', header = TRUE)
sample_coord8 <- read.table(file = '../laser/results.8751-10000.ProPC.coord', sep = '\t', header = TRUE)
sample_coord9 <- read.table(file = '../laser/results.10001-11250.ProPC.coord', sep = '\t', header = TRUE)
sample_coord10 <- read.table(file = '../laser/results.11251-12500.ProPC.coord', sep = '\t', header = TRUE)
sample_coord11 <- read.table(file = '../laser/results.12501-13750.ProPC.coord', sep = '\t', header = TRUE)
sample_coord12 <- read.table(file = '../laser/results.13751-15000.ProPC.coord', sep = '\t', header = TRUE)
sample_coord13 <- read.table(file = '../laser/results.15001-16250.ProPC.coord', sep = '\t', header = TRUE)
sample_coord14 <- read.table(file = '../laser/results.16251-17500.ProPC.coord', sep = '\t', header = TRUE)
sample_coord15 <- read.table(file = '../laser/results.17501-18750.ProPC.coord', sep = '\t', header = TRUE)
sample_coord16 <- read.table(file = '../laser/results.18751-20000.ProPC.coord', sep = '\t', header = TRUE)
sample_coord17 <- read.table(file = '../laser/results.20001-21250.ProPC.coord', sep = '\t', header = TRUE)
sample_coord18 <- read.table(file = '../laser/results.21251-21608.ProPC.coord', sep = '\t', header = TRUE)

sample_coord <- rbind(sample_coord1,sample_coord2,sample_coord3,sample_coord4,sample_coord5,sample_coord6,sample_coord7,sample_coord8,sample_coord9,sample_coord10,sample_coord11,sample_coord12,sample_coord13,sample_coord14,sample_coord15,sample_coord16,sample_coord17,sample_coord18)
ORIEN_TCGA_coord <- sample_coord[,c(1,2,7:12)]
```

```{r}
clinlinkage <- read.csv("../admix/20PRJ071USC_20210928_ClinicalMolLinkage_V4.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
key_SLID <- subset(clinlinkage, Tumor.Germline == "Germline")
key_SLID2 <- key_SLID[,c(1,3)]
demos <- read.csv("../admix/20PRJ071USC_20210928_PatientMaster_V4.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
demos2 <- demos[,c(1,5,6)]
names(key_SLID2)[names(key_SLID2 ) == "ORIENAvatarKey" ] <- "AvatarKey"
merge <- merge(x = key_SLID2,y = demos2, by='AvatarKey', sort=FALSE, all=TRUE)
names(merge)[names(merge ) == "WES" ] <- "indivID"
merge2 <- merge[,c(2,3,4)]

USC <-  read.csv("../admix/20211203_USC_ClinicalMolLinkage_V4.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
names(USC)[names(USC ) == "ORIENAvatarKey" ] <- "key"
key <- read.csv("../admix/V4_RecordKey_Jan2022.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
names(key)[names(key ) == "Avatar.Patient.ID" ] <- "key"
key <- key[,c(4,6,7)]
USC2 <- merge(x=USC, y=key, by="key")
USC2 <- USC2[,c(4,21,22)]
names(USC2)[names(USC2 ) == "WES" ] <- "indivID"
all <- bind_rows(merge2,USC2)
all <- all[-which(all$indivID == ""), ]

all[all$Race == "Black",]$Race = "Black_or_African_American"
all[all$Race == "Unknown/Not Reported",]$Race = "Unknown/Not_Reported"
all[all$Race == "Other Asian, including Asian, NOS and Oriental, NOS",]$Race = "Asian"
all[all$Race == "Filipino",]$Race = "Asian"
all[all$Race == "Chinese",]$Race = "Asian"
all[all$Race == "Korean",]$Race = "Asian"
all[all$Race == "American Indian, Aleutian, or Eskimo (includes all indigenous populations of the Western Hemisphere)",]$Race = "American_Indian_or_Alaska_Native"
all[all$Race == "American Indian, Aleutian, or Eskimo (includes all indigenous populations of the Western hemisphere)",]$Race = "American_Indian_or_Alaska_Native"
all[all$Race == "Asian Indian or Pakistani, NOS",]$Race = "Asian"
all[all$Race == "Asian Indian",]$Race = "Asian"
all[all$Race == "Vietnamese",]$Race = "Asian"
all[all$Race == "Japanese",]$Race = "Asian"
all[all$Race == "Pacific Islander, NOS",]$Race = "Hawaiian_or_Other_Pacific_Islander"
all[all$Race == "Unknown/Not Applicable",]$Race = "Unknown/Not_Reported"
all[all$Race == "Hawaiian",]$Race = "Hawaiian_or_Other_Pacific_Islander"
all[all$Race == "Laotian",]$Race = "Asian"
all[all$Race == "Pakistani",]$Race = "Asian"
all[all$Race == "Kampuchean (Cambodian)",]$Race = "Asian"
all[all$Race == "Polynesian, NOS",]$Race = "Hawaiian_or_Other_Pacific_Islander"
all[all$Race == "Thai",]$Race = "Asian"
all[all$Race == "Guamanian, NOS",]$Race = "Hawaiian_or_Other_Pacific_Islander"

all[all$Ethnicity == "Non-Spanish; Non-Hispanic",]$Ethnicity = "Not_Hispanic/Not_Latino" 
all[all$Ethnicity == "Spanish, NOS; Hispanic, NOS; Latino, NOS",]$Ethnicity = "Hispanic/Latino"
all[all$Ethnicity == "Unknown/Not Reported",]$Ethnicity = "Unknown/Not_Reported"
all[all$Ethnicity == "Mexican (includes Chicano)",]$Ethnicity = "Hispanic/Latino"
all[all$Ethnicity == "South or Central American (except Brazil)",]$Ethnicity = "Hispanic/Latino"
all[all$Ethnicity == "Puerto Rican",]$Ethnicity = "Hispanic/Latino"
all[all$Ethnicity == "Unknown/Not Applicable",]$Ethnicity = "Unknown/Not_Reported"
all[all$Ethnicity == "Cuban",]$Ethnicity = "Hispanic/Latino"
all[all$Ethnicity == "Other specified Spanish/Hispanic origin (includes European; excludes Dominican Republic)",]$Ethnicity = "Hispanic/Latino"
all[all$Ethnicity == "Spanish surname only",]$Ethnicity = "Hispanic/Latino"
all[all$Ethnicity == "Dominican Republic",]$Ethnicity = "Hispanic/Latino"


TCGA_race <- read.csv("../admix/TCGA_vcfIDs_race_uniq_final.tsv", sep = "\t", header = FALSE, stringsAsFactors = FALSE, fill = TRUE)
TCGA_ethnicity <- read.csv("../admix/TCGA_vcfIDs_ethnicity_uniq_final.tsv", sep = "\t", header = FALSE, stringsAsFactors = FALSE, fill = TRUE)
names(TCGA_race)[2] <- "Race"
names(TCGA_ethnicity)[2] <- "Ethnicity"
names(TCGA_race)[1] <- "indivID"
names(TCGA_ethnicity)[1] <- "indivID"
TCGA <- merge(x = TCGA_race, y = TCGA_ethnicity, by="indivID")

merge5 <- bind_rows(TCGA,all)

race <- merge5[,c(1,2)]
names(race)[names(race) == "Race"] <- "Race"
ethnicity <- merge5[,c(1,3)]
names(ethnicity)[names(ethnicity) == "Ethnicity"] <- "Ethnicity"

str_replace(race$indivID, "_st_g", "")
str_replace(ethnicity$indivID, "_st_g", "")
```

```{r}
ORIEN_TCGA_coord <- ORIEN_TCGA_coord[,c(2:4)]
admix.props <- samples[,c(1:6)]
coords <- ORIEN_TCGA_coord[,c(1:3)]

df <- merge(admix.props, coords, by="indivID")
df2 <- merge(df, race, by="indivID")
df3 <- merge(df2, ethnicity, by="indivID")

HL <- subset(df3, df3$Ethnicity == "Hispanic/Latino")
Black <- subset(df3, df3$Race == "Black_or_African_American")
Asian <- subset(df3, df3$Race == "Asian")
Indigenous <- subset(df3, df3$Race == "American_Indian_or_Alaska_Native")
Pacific <- subset(df3, df3$Race == "Hawaiian_or_Other_Pacific_Islander")
```

```{r}
data <- df3
admix.props2 <- as.matrix.data.frame(data[,c(2:6)])
coords2 <- as.matrix.data.frame(data[,c(7,8)])

jpeg(file = "All_ORIEN_TCGA_pie_charts_of_admixture_plotted_on_LASER_PCA_coordinates.jpeg", width=10, height=5, units="in", res=1000)
make.admix.pie.plot(admix.proportions = admix.props2,
                        coords = coords2,
                        radii = 1.5)
dev.off()
```

```{r}
data <- HL
admix.props2 <- as.matrix.data.frame(data[,c(2:6)])
coords2 <- as.matrix.data.frame(data[,c(7,8)])

jpeg(file = "Hispanic_Latino_ORIEN_TCGA_pie_charts_of_admixture_plotted_on_LASER_PCA_coordinates.jpeg", width=10, height=5, units="in", res=1000)
make.admix.pie.plot(admix.proportions = admix.props2,
                        coords = coords2,
                        radii = 1.5)
dev.off()
```

```{r}
data <- Black
admix.props2 <- as.matrix.data.frame(data[,c(2:6)])
coords2 <- as.matrix.data.frame(data[,c(7,8)])
jpeg(file = "Black_African_American_ORIEN_TCGA_pie_charts_of_admixture_plotted_on_LASER_PCA_coordinates.jpeg", width=10, height=5, units="in", res=1000)
make.admix.pie.plot(admix.proportions = admix.props2,
                        coords = coords2,
                        radii = 2)

dev.off()
```


```{r}
data <- Asian
admix.props2 <- as.matrix.data.frame(data[,c(2:6)])
coords2 <- as.matrix.data.frame(data[,c(7,8)])
jpeg(file = "Asian_ORIEN_TCGA_pie_charts_of_admixture_plotted_on_LASER_PCA_coordinates.jpeg", width=10, height=5, units="in", res=1000)
make.admix.pie.plot(admix.proportions = admix.props2,
                        coords = coords2,
                        radii = 2)
dev.off()
```

```{r}
data <- Indigenous
admix.props2 <- as.matrix.data.frame(data[,c(2:6)])
coords2 <- as.matrix.data.frame(data[,c(7,8)])
jpeg(file = "American_Indian_ORIEN_TCGA_pie_charts_of_admixture_plotted_on_LASER_PCA_coordinates.jpeg", width=10, height=5, units="in", res=1000)
make.admix.pie.plot(admix.proportions = admix.props2,
                        coords = coords2,
                        radii = 2)
dev.off()
```


```{r}
data <- Pacific
admix.props2 <- as.matrix.data.frame(data[,c(2:6)])
coords2 <- as.matrix.data.frame(data[,c(7,8)])
jpeg(file = "Pacific_Islander_ORIEN_TCGA_pie_charts_of_admixture_plotted_on_LASER_PCA_coordinates.jpeg", width=10, height=5, units="in", res=1000)
make.admix.pie.plot(admix.proportions = admix.props2,
                        coords = coords2,
                        radii = 2)
dev.off()
```